name: Deploy StylixOS Homepages

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_ROOT }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repository
        shell: bash
        run: |
          git clone --depth 1 git@gitlab.com:stylixos/homepage.git source

      - name: Prepare site
        shell: bash
        run: |
          mkdir -p site
          cp -a source/x86_64 site/
          cp -a source/index.html site/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
